import { createRoute } from '@tanstack/react-router'
import { Route as rootRoute } from "./__root"; // We import root as an alias
import React from "react";
import { LegalPage, LegalSection } from "@/components/genesys/legal";
import { Navbar } from "@/components/genesys/navbar";
import { Footer } from "@/components/genesys/footer";

export const Route = createRoute({
  getParentRoute: () => rootRoute,
  path: "/terms",
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="bg-slate-50">
      <Navbar />
      <LegalPage
        title="Terms & Conditions"
        subtitle="The rules of the Genesys AI Core"
        lastUpdated="September 25, 2026"
      >
        <LegalSection title="1. Agreement to terms">
          <p>By using Genesys AI, you agree to these autonomous system protocols.</p>
        </LegalSection>

        <LegalSection title="2. Intellectual Property">
          <p>You own the code generated by the agent. We own the bridge technology.</p>
        </LegalSection>

        <LegalSection title="3. Payments">
          <p>Payments are handled securely via Paddle.com.</p>
        </LegalSection>
      </LegalPage>
      <Footer />
    </div>
  );
}
